f=open('5.txt','w')
f.write('红豆生南国\n')
f.write('春来发几枝\n')
f.write('愿君多采霞\n')
f.write('此物最相思\n')
f.close()

f=open('5.txt','r')
c=f.readline()
p=f.tell()
print('读取第一行的内容是：%s'%c)
print('读取第一行的游标位置是：%d'%p)
c=f.readline()
p=f.tell()
print('读取第二行的内容是：%s'%c)
print('读取第二行的游标位置是：%d'%p)
c=f.readline()
p=f.tell()
print('读取第三行的内容是：%s'%c)
print('读取第三行的游标位置是：%d'%p)
c=f.readline()
p=f.tell()
print('读取第四行的内容是：%s'%c)
print('读取第四行的游标位置是：%d'%p)
'''
#定位seek
f=open('1.txt','rb+')
f.write('\n')
f.close()
c=f.readline()#c变量用于保存readline返回的一行内容
p=f.tell()#p变量用于保存tell返回的游标位置
print('读取的第一行内容是:%s'%c)
print('读取第一行的游标位置是%d'%p)
f.seek(0,0)
print(f.readline())#重新返回第一行读取
f.seek(-3,2)
print(f.tell())
f.close()
'''
