#coding=utf-8
#输入西瓜的单价
price=float(input("请您输入西瓜的价格"))
#输入西瓜的重量
weight=float(input("请您输入西瓜的重量"))
#计算西瓜的总额
money=price*weight
print("该西瓜的单价是%.2f元"%(price))
print("该西瓜的重量是%.2f元"%(weight))
print("该西瓜的总额是%.2f元"%(money))
